### ISSUE TITLE
Todo nach erstem Test

### ISSUE THREAD

**Issue by McDiod** [gruppe-adler/TvT_GameOfGuns.Altis#2]
- [x] Spielzonen Voting
- [x] Gear on Respawn
- [x] automatische Spielzonengröße
- [x] restliches Gear bei Waffenupgrade (Bandagen, etc.)
- [x] ACE_medical_lastDamageSource wird über den Tot hinaus gespeichert: bei Esc-->Respawn bekommt die letzte Source den Kill
- [x] Uniformauswahl
- [x] bessere Waffen als tier1 hinzufügen
- [x] upgradeWeapon Bild der neuen Waffe als Title
